# Generated by Django 6.1.1 on 2026-09-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('cloud_provider', models.CharField(choices=[('aws', 'Amazon Web Services'), ('gcp', 'Google Cloud Platform'), ('azure', 'Microsoft Azure'), ('upcloud', 'UpCloud')], default='aws', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('service_type', models.CharField(choices=[('pg', 'PostgreSQL'), ('mysql', 'MySQL'), ('kafka', 'Apache Kafka'), ('redis', 'Redis'), ('opensearch', 'OpenSearch'), ('clickhouse', 'ClickHouse')], default='pg', max_length=20)),
                ('plan', models.CharField(choices=[('hobbyist', 'Hobbyist (1 Node, 1GB RAM)'), ('startup-4', 'Startup-4 (1 Node, 4GB RAM)'), ('business-8', 'Business-8 (2 Nodes, 8GB RAM)'), ('premium-16', 'Premium-16 (3 Nodes, 16GB RAM)')], default='startup-4', max_length=20)),
                ('state', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('REBUILDING', 'Rebuilding'), ('MAINTENANCE', 'Maintenance')], default='RUNNING', max_length=20)),
                ('disk_space_mb', models.PositiveIntegerField(default=10240, help_text='Disk space in MB')),
                ('node_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='aiven.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_pct', models.FloatField(help_text='CPU usage percentage (0 - 100)')),
                ('memory_usage_pct', models.FloatField(help_text='Memory usage percentage (0 - 100)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='aiven.service')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
