# Generated by Django 6.1.1 on 2026-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiven', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(default='postgres', max_length=50),
        ),
        migrations.DeleteModel(
            name='ServiceMetric',
        ),
        migrations.RemoveField(
            model_name='service',
            name='disk_space_mb',
        ),
        migrations.RemoveField(
            model_name='service',
            name='node_count',
        ),
        migrations.RemoveField(
            model_name='service',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='service',
            name='project',
        ),
        migrations.RemoveField(
            model_name='service',
            name='state',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
