# Generated by Django 6.1.1 on 2026-09-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiven', '0002_alter_service_options_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aiven Service', 'verbose_name_plural': 'Aiven Services'},
        ),
    ]
